FORMAT: 1A
HOST: http://localhost:8000/v1

# SGPF (Profisco)

Sistema de Gestão de Projetos Financiados. API responsável por fornecer recursos/dados
para a construção do sistema web SGPF. 

# Group Cadastros Básicos

## Programas de Financiamento [/programa-financiamentos]

### Criar Programa Financiamento [POST]

+ Request Criar novo programa financiamento

    + Headers

            Accept: text/plain
        	Content-Type: application/json
    + Attributes (ProgramaFinanciamento)

+ Response 200 (application/json)
    + Attributes (DefaultSuccessfulResponse)

### Listar Programas Financiamento [GET]

+ Response 200 (application/json)
	+ Attributes (object)
        + data (array[ProgramaFinanciamento]) - Array dos Programas Financiamento
        + links (DefaultLinks) - Links para auxilio API.
        + meta (DefaultMetas) - Metadados

+ Response 404 (application/json)
    + Attributes (DefaultErrorResponse)

## Programa Financiamento [/programa-financiamentos/{id_programa_financiamento}]

+ Parameters
    + id_programa_financiamento: 1 (number, required) - ID do Programa Financiamento

### Ver Programa Financiamento [GET]

+ Response 200 (application/json)
    + Attributes (object)
        + data (array[ProgramaFinanciamento]) - Programas Financiamento
        + links (DefaultLinks) - Links para auxilio API.
        + meta (DefaultMetas) - Metadados

+ Response 404 (application/json)
    + Attributes (DefaultErrorResponse)

### Excluir Programa Financiamento [DELETE]

+ Response 200 (application/json)
    + Attributes (DefaultSuccessfulResponse)

+ Response 404 (application/json)
    + Attributes (DefaultErrorResponse)

### Alterar Programa Financiamento [PUT]

+ Request Alterar um programa financiamento

    + Headers

            Accept: application/json
            Content-Type: application/json
    + Attributes (ProgramaFinanciamento)

+ Response 200 (application/json)
    + Attributes (DefaultSuccessfulResponse)

+ Response 400 (application/json)
    + Attributes (DefaultErrorResponse)

## Categorias [/categorias]

### Criar Categoria [POST]

+ Request Criar nova categoria

    + Headers

            Accept: text/plain
        	Content-Type: application/json
    + Attributes (Categoria)

+ Response 200 (application/json)
    + Attributes (DefaultSuccessfulResponse)

### Listar Categorias [GET]

+ Response 200 (application/json)
	+ Attributes (object)
        + data (array[Categoria]) - Array de Categorias
        + links (DefaultLinks) - Links para auxilio API.
        + meta (DefaultMetas) - Metadados

+ Response 404 (application/json)
    + Attributes (DefaultErrorResponse)

## Categoria [/categorias/{id_categoria}]

+ Parameters
    + id_categoria: 1 (number, required) - ID da Categoria

### Ver Categoria [GET]

+ Response 200 (application/json)
    + Attributes (object)
        + data (array[Categoria]) - Categoria Object
        + links (DefaultLinks) - Links para auxilio API.
        + meta (DefaultMetas) - Metadados

+ Response 404 (application/json)
    + Attributes (DefaultErrorResponse)

### Excluir Categoria [DELETE]

+ Response 200 (application/json)
    + Attributes (DefaultSuccessfulResponse)

+ Response 404 (application/json)
    + Attributes (DefaultErrorResponse)

### Alterar Categoria [PUT]

+ Request Alterar uma categoria

    + Headers

            Accept: application/json
            Content-Type: application/json
    + Attributes (Categoria)

+ Response 200 (application/json)
    + Attributes (DefaultSuccessfulResponse)

+ Response 400 (application/json)
    + Attributes (DefaultErrorResponse)

## Componentes [/componentes]

### Criar Componente [POST]

+ Request Criar novo componente

    + Headers

            Accept: text/plain
        	Content-Type: application/json
    + Attributes (Componente)

+ Response 200 (application/json)
    + Attributes (DefaultSuccessfulResponse)

### Listar Componentes [GET]

+ Response 200 (application/json)
	+ Attributes (object)
        + data (array[Componente]) - Array de Componentes
        + links (DefaultLinks) - Links para auxilio API.
        + meta (DefaultMetas) - Metadados

+ Response 404 (application/json)
    + Attributes (DefaultErrorResponse)

## Componente [/componentes/{id_componente}]

+ Parameters
    + id_componente: 1 (number, required) - ID do Componente

### Ver Componente [GET]

+ Response 200 (application/json)
    + Attributes (object)
        + data (array[Componente]) - Componente Object
        + links (DefaultLinks) - Links para auxilio API.
        + meta (DefaultMetas) - Metadados

+ Response 404 (application/json)
    + Attributes (DefaultErrorResponse)

### Excluir Componente [DELETE]

+ Response 200 (application/json)
    + Attributes (DefaultSuccessfulResponse)

+ Response 404 (application/json)
    + Attributes (DefaultErrorResponse)

### Alterar Componente [PUT]

+ Request Alterar um componente

    + Headers

            Accept: application/json
            Content-Type: application/json
    + Attributes (Componente)

+ Response 200 (application/json)
    + Attributes (DefaultSuccessfulResponse)

+ Response 400 (application/json)
    + Attributes (DefaultErrorResponse)

# Data Structures

## Componente (object)
+ nome (string) - Nome do Componente
+ numero (number) - Numero do Componente
+ lider (string) - Nome do Líder
+ programa_trabalho (string) - Nome do Programa de trabalho
+ id_categoria (number) - Relacionamento chave estrangeira Categoria
+ categoria (Categoria) - Objeto mapeado Categoria


## Categoria (object)
+ nome (string) - Nome da Categoria
+ sigla (string) - Sigla da Categoria
+ id_programa_financiamento (number) - Relacionamento chave estrangeira Programa Financiamento
+ programa_financiamento (ProgramaFinanciamento) - Objeto mapeado Programa Financiamento

## ProgramaFinanciamento (object)
+ numero_contrato (string) - Número do Contrato
+ data_assintura (string) - Data da Assintura do Contrato
+ nome (string) - Nome do Programa Financiamento
+ descricao (string) - Texto Descritivo do Programa Financiamento
+ orgao_financiador (string) - Nome/Descrição do órgão financiador

## DefaultLinks (object)
+ first (string) - First
+ last (number) - Last
+ prev (string) - Prev
+ next (string) - Next

## DefaultMetas (object)
+ current_page (number) - Current Page
+ from (number) - From 
+ last_page (number) - Last Page
+ path (string) - Path
+ per_page (number) - Per Page
+ to (number) - To
+ total (number) - Total

## DefaultSuccessfulResponse (object)
+ id (number) - Id gerado
+ status_code: 200 (number) - Código Http do Response
+ mensagem (string) - Mensagem de retorno

## DefaultErrorResponse (object)
+ status_code: 400 (number) - Status code
+ mensagem (string) - Mensagem do status
+ descricao (string) - Descrição do status
+ code: 2 (number) - Sub código.